spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  datasource:
    # TODO: fix mentor comment and move sensitive data(db creds) to AWS Param Store
    url: jdbc:postgresql://postgres:5432/resource
    username: postgres
    password: postgres
  cloud:
    stream:
      bindings:
        producer-out-0:
          destination: resource-ids
          group: resource-processor
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    template:
      retry:
        enabled: true
        initial-interval: 5000ms
        max-attempts: 2

aws:
  s3:
    endpoint-url: http://localstack:4566
    bucket-name: resources
    region: us-east-1

logging:
  level:
    root: info
    com:
      amazonaws:
        internal:
          InstanceMetadataServiceResourceFetcher: error
        util:
          EC2MetadataUtils: error

server:
  tomcat:
    max-swallow-size: 20MB
    max-http-form-post-size: 20MB
  port: 8080

services:
  url:
    song-service: http://song-service-app:8081/api/v1/songs
