spring:
  datasource:
    # TODO: fix mentor comment and move sensitive data(db creds) to AWS Param Store
    url: jdbc:postgresql://postgres:5432/storage
    username: postgres
    password: postgres
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloack:8080/realms/microservices
          # jwk-set-uri: http://keycloack:8080/realms/microservices/protocol/openid-connect/certs
          # jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

server:
  port: 8085
  
